name: test
on:
  workflow_call:
    inputs:
      disable-windows:
        description: Disable running tests on Windows
        type: boolean
        default: false
        required: false

jobs:
  test_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/krypton', 'latest']

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run quick:test
        env:
          NODE_ENV: test
          DB_CONNECTION: pg
          PG_TEST_DATABASE_URL: postgres://user:password@localhost:5432/test_db

  test_windows:
    if: ${{ !inputs.disable-windows }}
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: ['lts/krypton', 'latest']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run quick:test
        env:
          DB_CONNECTION: sqlite # Use SQLite for Windows since Postgres service is not available
